# This file is part of twittergeo.
# https://github.com/fitnr/twittergeo

# Licensed under the GNU General Public License v3 (GPLv3) license:
# http://opensource.org/licenses/GPL-3.0
# Copyright (c) 2015, Neil Freeman <contact@fakeisthenewreal.org>

language: python

python:
    - pypy
    - pypy3
    - 2.7
    - 3.3
    - 3.4
    - 3.5

install:
    - python setup.py install

script:
    - python setup.py test
